witch={"Will":{"status":['HP:65', 'Power:85','Defence:70','Speed:80', 'Total:300'],
                "skills":['Thunder Bolt', 'Energy Explosion', 'Lightning Sphere'],
                "type": ['#1', 'Quintessential'],
                "others":['images_witch/will.png', '#e2558b']},
        "Irma":{"status":['HP:100', 'Power:75','Defence:60','Speed:65', 'Total:300'],
                "skills":['Water Slap', 'Whirpool Loop', 'Icecle Downpour'],
                "type": ['#2', 'Water/Ice'],
                "others":['images_witch/irma.png', '#1282ba']},
        "Taranee":{"status":['HP:70', 'Power:90','Defence:70','Speed:70', 'Total:300'],
                "skills":['Flame Thrower', 'Lava Rain', 'Inferno Burst'],
                "type": ['#3', 'Fire'],
                "others":['images_witch/taranee.png', '#ce540d']},
        "Cornelia":{"status":['HP:75', 'Power:80','Defence:95','Speed:50', 'Total:300'],
                "skills":['Stone Spurt', 'Rock Eduction', 'Forest Furiosness'],
                "type": ['#4', 'Earth'],
                "others":['images_witch/corni.png', '#468311']},
        "Hay Lin":{"status":['HP:70', 'Power:70','Defence:60','Speed:100', 'Total:300'],
                "skills":['Air Blast', 'Tornado Rampage', 'Shock Wave Blast'],
                "type": ['#5', 'Air/Blast'],
                "others":['images_witch/haylin.png', '#3b9167']}
}